# -*- coding: utf-8 -*-
"""Copy of DAY7_RNN_Trail_DA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U92aSpK_8TGKxHkjnii9gvcr7I_fpUct
"""

import numpy as np
from keras.models import Sequential
from keras.layers import SimpleRNN,Dense,Embedding
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from keras.utils import to_categorical



import pandas as pd
df=pd.read_csv("/content/Earth.txt",sep=".")
df

#Tokenizing the words
tokenizer=Tokenizer()
tokenizer.fit_on_texts(df)
total_words=len(tokenizer.word_index)+1
print(total_words)

# Creating input sequences and their corresponding next words
input_sequences = []
for sentence in df:
    tokenized_sentence = tokenizer.texts_to_sequences([sentence])[0]
    for i in range(1, len(tokenized_sentence)):
        n_gram_sequence = tokenized_sentence[:i+1]
        input_sequences.append(n_gram_sequence)
input_sequences