# -*- coding: utf-8 -*-
"""DA_DAy6_Aft_project_cancer.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rOU_GxPh4W7gkdCcgep3h-oMSpyEGQzZ
"""

from sklearn.linear_model import LinearRegression
LR=LinearRegression()

c=[[2],[1],[2],[1],[2]]
cp=[2,2,2,2,1]
LR.fit(c,cp)

LR.predict([[2]])

#plot the data and the linear regression line
from matplotlib import pyplot as plt
plt.scatter(c,cp,color='black')
y_pred=LR.predict(c)
plt.plot(c,y_pred,color='blue',linewidth=3)
plt.xlabel('COUGHING')
plt.ylabel('CHEST PAIN')
plt.title('Linear Regression')
plt.show()

#plot the data
from matplotlib import pyplot as plt
plt.plot(c,cp,color='black')
#linear regression line
y_pred=LR.predict(c)
print(y_pred)
plt.plot(c,y_pred,color='blue',linewidth=3,marker="H")
plt.xlabel('COUGHING')
plt.ylabel('CHEST PAIN')
plt.title('Linear Regression')
plt.show()

import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import export_graphviz,plot_tree
from IPython.display import Image

df= pd.read_csv('/content/survey lung cancer.csv')
df

from sklearn.tree import DecisionTreeClassifier

target=df["LUNG_CANCER"]
print(target)

feature_list=['AGE','SMOKING','YELLOW_FINGERS','CHRONIC DISEASE','SWALLOWING DIFFICULTY','CHEST PAIN']
features=df[feature_list]
print(features)

model=DecisionTreeClassifier()
model.fit(features,target)

DT=model.fit(features,target)

from sklearn.tree import plot_tree

plot_tree(DT)

Age=int(input("Enter Age: "))
Smoking=int(input("Enter he is smoking or not: "))
Yellow_Fingers=int(input("Enter the Yellow_Fingers: "))
Chronic=int(input("Enter the Chronic Disease: "))
Swallowing=int(input("Enter he is swallowing or not: "))
Chest=int(input("Enter he is feeling from Chest pain or not: "))
pred=model.predict([[Age,Smoking,Yellow_Fingers,Chronic,Swallowing,Chest]])
if pred==True:
  print("he is suffering with lung disease")
else:
  print("he is alright!")
print(pred)

"""RandomForestClassifier

"""

from sklearn.ensemble import RandomForestClassifier

#n_estimators gives the number of trees
from sklearn.linear_model import LinearRegression
model=RandomForestClassifier(n_estimators=10) #create RandamForestClassifier
model.fit(features,target)

#saving all Decision trees
import os
output_dir="tree_visualizations"
os.makedirs(output_dir,exist_ok=True) #Created folder in files

for i,tree in enumerate(model.estimators_):
  tree_dot_file=os.path.join(output_dir,f"tree-{i}.dot")
  tree_png_file=os.path.join(output_dir,f"tree-{i}.png")

from sklearn.tree import export_graphviz
export_graphviz(tree, out_file=tree_dot_file, feature_names=["Age","Smoking","Yellow_Fingers","Chronic","Swallowing","Chest",],
                    class_names=[str(cls) for cls in model.classes_], filled=True, rounded=True)

command=f"dot -Tpng {tree_dot_file} -o {tree_png_file}"
os.system(command)
print(f"Tree {i} visualization saved to {tree_png_file}")