# -*- coding: utf-8 -*-
"""Day2_DA_Plotting.jpynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/191K1BKtP1Wc28hAYbULBYkHK1YjjhqYU
"""

from matplotlib import pyplot as plt

#plotting a graph
x=[1,2,3,4,5,6,7,8]
y=[34,56,78,12,34,23,14,4]
plt.plot(x,y) #line graph
plt.title("My first plot")
plt.xlabel('x values')
plt.ylabel('y values')
#tile labels legend color width markers

#problem statement
#there are 5 subjects : psychology,nanotechnology,medicine,oncology,anthropology.........Two students have applied to do masters in any of five fields......
#with the line plot show in which the field they excel.......The cut of each subject is 70
#now st1=[67,45,73,71,57]
#now std2=[43,67,68,53,85]
sub=['psych','nano','med','onco','anthro']
s1=[67,45,73,71,57]
s2=[43,67,68,53,85]
cut=[70,70,70,70,70]
#student1
plt.plot(sub,s1,label='student1',color='k',marker='P',linewidth=3)
#student2
plt.plot(sub,s2,label='student2',color='b',marker='H') ##plot ->> scatter -->> ->>dots
#cutoff
plt.plot(sub,cut,label='cutoff',color='r',marker='p',linestyle=':')
plt.xlabel('subjects')
plt.ylabel('marks')
plt.legend()
###markers dot shapes for scatter
#linestyle ::::::

#problem statement
#an india vs aus match is on live.India has given 298 as target for aus.The runs for every 5 over is as follows :#######india scores=[25,51,84,131,160,189,220,250,267,297]#aus have completed only 25 overs :######aus scores=[15,41,94,110,151]
#plot between overs vs runs #plot both the countries as india blue line and aus as yellow line
#give require labels and legends,the marker for india is flag and marker for aus is plus
#create overs from arange function. create runs as arrays. linewidth=2. marker=">"
import numpy as np
ind=np.array([25,51,84,131,160,189,220,250,267,297])
aus=np.array([15,41,94,110,151])
ind_overs=np.arange(5,51,5)
plt.plot(ind_overs,ind,label="INDIA",color='b',linewidth=2,marker='>')
aus_overs=np.arange(5,26,5)
plt.plot(aus_overs,aus,label="Austrailia",color='yellow',linewidth=2,marker='P')
plt.xlabel('overs')
plt.ylabel('runs')
plt.title("IND vs Aus")
plt.legend()
plt.grid()