# -*- coding: utf-8 -*-
"""DAY3_Pandas_seabound.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eNQ_F-eywDCSmOdjS4cXqhuCv9BXKFls
"""

import pandas as pd

a=pd.read_csv("/content/mydf.csv")
a

import seaborn as sns

pl=sns.lineplot(x='Names',y='SEM1',data=a)

sns.relplot(data=a,x='SEM1',y='Names',col='Placed')

##col--->>graphs are seperated on this column

dxl=pd.read_excel("/content/diabetes.xlsx")
dxl

#Problem statement
#create a relational plot using age as y-axis,index as x-axis seperated by class
#diabatis.excel
dxl['Index']=range(1,769)
dxl

#Problem statement With answer
#create a relational plot using age as y-axis,index as x-axis seperated by class
#diabatis.excel
dxl['Index']=range(1,769)
sns.relplot(data=dxl,x='Index',y='age',col='class')

tips=sns.load_dataset("tips")    #tips,fmri,dowjones......
tips



sns.relplot(data=tips,x='total_bill',y='tip',hue='size',style='time',palette='bright')
#hue-->creating difference based on a column via colors
#palette=color brightness

dowjones=sns.load_dataset("dowjones")
dowjones.head()

sns.relplot(data=dowjones,x='Date',y='Price',kind='line')

fmri=sns.load_dataset("fmri")
fmri.head()

sns.relplot(data=fmri,x='timepoint',y='signal',kind='line')

sns.catplot(data=tips,x='total_bill',y='smoker')

sns.catplot(data=tips,y='total_bill',x='time',hue='smoker',kind='violin')

sns.catplot(data=tips,y='total_bill',x='time',kind='violin')

sns.catplot(data=tips,y='total_bill',x='time',hue='smoker',kind='box')