# -*- coding: utf-8 -*-
"""DAY4_WS_Selenium_HOMEWORK.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xDza_rv-tmapapfpi5y3t8mr41w7M0B_
"""

from bs4 import BeautifulSoup
import requests as req

url="https://en.m.wikipedia.org/wiki/List_of_tallest_buildings_in_India"
page=req.get(url)
code=BeautifulSoup(page.text,'html')
print(code)

t=code.find('title')
print(t)

t=code.find('table')
print(t)

t1=t.find_all('th')
t1

heading=[i.text for i in t1]
heading

import pandas as pd

mydf=pd.DataFrame(columns=heading)
print(mydf)

rows=t.find_all('tr')
rows

data=t.find_all('td')
data

data_act=[i.text for i in data]
data_act

df1=pd.DataFrame(columns=['rank','name','image','city','heaight','floors','year','bd','reference'])
df1

data_act[0:9]

print(len(data_act))

index=0
start=0
stop=9
for i in range(len(data_act)//9):
  mydf.loc[index]=data_act[start:stop]
  start=start+9
  stop=stop+9
  index=index+1
mydf

mydf.to_csv("buildings.csv")