# -*- coding: utf-8 -*-
"""DAY5_API.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lQeD6w1v-kS8xMvp6mW0T2yAb3KeZAEi
"""

import requests
api_key="3e1deda2318d4d3793760706242802"
city='Hyderabad'
url=f"http://api.weatherapi.com/v1/current.json?key={api_key}&q={city}"
response=requests.get(url)
data=response.json()
print(data)

type(data)

import requests
api_key="3e1deda2318d4d3793760706242802"
city=input('Enter a city name : ')
url=f"http://api.weatherapi.com/v1/current.json?key={api_key}&q={city}"
response=requests.get(url)
data=response.json()
print(data)

print("city",data['location']['name'])
print("state",data['location']['region'])
print("country",data['location']['country'])
print("temperature",data['current']['temp_c'])
print("wind direction",data['current']['wind_dir'])
print("wind speed"),data['current']['wind_mph']
print("humidity"),data['current']['humidity']
print("feels like"),data['current']['feelslike_c']

import requests
api_key="3e1deda2318d4d3793760706242802"
city=input('Enter a city name : ')
url=f"http://api.weatherapi.com/v1/current.json?key={api_key}&q={city}"
response=requests.get(url)
data=response.json()
if response.status_code==200:
  print("city",data['location']['name'])
  print("state",data['location']['region'])
  print("country",data['location']['country'])
  print("temperature",data['current']['temp_c'])
  print("wind direction",data['current']['wind_dir'])
  print("wind speed"),data['current']['wind_mph']
  print("humidity"),data['current']['humidity']
  print("feels like"),data['current']['feelslike_c']
else :
  print(data['error']['message'])

