# -*- coding: utf-8 -*-
"""DAY6_csv_project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10OcJeB4xTnb5GcrjF8UHG4OELE4NnQ2P
"""

import pandas as pd



from sklearn.linear_model import LinearRegression
LR=LinearRegression()

df=pd.read_csv("/content/spam.csv",encoding="latin-1")
df

feature_col=['v2']
feature=df[feature_col]
target=df.v1

df['status'] = df['v1'].apply(lambda x: 0 if x=='spam' else 1)

df

status=int(input("Enter Status:"))
if status==1:
  print("ham")
else:
  print("spam")